// <auto-generated />
using System;
using Dashboard.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Dashboard.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260216103759_dataSeeding")]
    partial class dataSeeding
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Dashboard.Domain.Entities.Agent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("LastStatusChange")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("Agents");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            LastStatusChange = new DateTime(2026, 2, 16, 8, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Ahmed Hassan",
                            Status = 0
                        },
                        new
                        {
                            Id = 2,
                            LastStatusChange = new DateTime(2026, 2, 16, 8, 15, 0, 0, DateTimeKind.Utc),
                            Name = "Sara Mohamed",
                            Status = 0
                        },
                        new
                        {
                            Id = 3,
                            LastStatusChange = new DateTime(2026, 2, 16, 8, 30, 0, 0, DateTimeKind.Utc),
                            Name = "Omar Ali",
                            Status = 1
                        },
                        new
                        {
                            Id = 4,
                            LastStatusChange = new DateTime(2026, 2, 16, 8, 45, 0, 0, DateTimeKind.Utc),
                            Name = "Nour Ibrahim",
                            Status = 2
                        },
                        new
                        {
                            Id = 5,
                            LastStatusChange = new DateTime(2026, 2, 16, 9, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Youssef Khaled",
                            Status = 0
                        });
                });

            modelBuilder.Entity("Dashboard.Domain.Entities.Call", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AgentId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("AnsweredAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("QueueId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AgentId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("QueueId");

                    b.HasIndex("Status");

                    b.ToTable("Calls");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AgentId = 1,
                            AnsweredAt = new DateTime(2026, 2, 16, 8, 6, 0, 0, DateTimeKind.Utc),
                            CreatedAt = new DateTime(2026, 2, 16, 8, 5, 0, 0, DateTimeKind.Utc),
                            QueueId = 1,
                            Status = 1
                        },
                        new
                        {
                            Id = 2,
                            AgentId = 2,
                            AnsweredAt = new DateTime(2026, 2, 16, 8, 12, 0, 0, DateTimeKind.Utc),
                            CreatedAt = new DateTime(2026, 2, 16, 8, 10, 0, 0, DateTimeKind.Utc),
                            QueueId = 1,
                            Status = 1
                        },
                        new
                        {
                            Id = 3,
                            AgentId = 5,
                            AnsweredAt = new DateTime(2026, 2, 16, 8, 21, 0, 0, DateTimeKind.Utc),
                            CreatedAt = new DateTime(2026, 2, 16, 8, 20, 0, 0, DateTimeKind.Utc),
                            QueueId = 2,
                            Status = 1
                        },
                        new
                        {
                            Id = 4,
                            AgentId = 1,
                            AnsweredAt = new DateTime(2026, 2, 16, 8, 27, 0, 0, DateTimeKind.Utc),
                            CreatedAt = new DateTime(2026, 2, 16, 8, 25, 0, 0, DateTimeKind.Utc),
                            QueueId = 3,
                            Status = 1
                        },
                        new
                        {
                            Id = 5,
                            AgentId = 2,
                            AnsweredAt = new DateTime(2026, 2, 16, 8, 36, 0, 0, DateTimeKind.Utc),
                            CreatedAt = new DateTime(2026, 2, 16, 8, 35, 0, 0, DateTimeKind.Utc),
                            QueueId = 2,
                            Status = 1
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2026, 2, 16, 8, 15, 0, 0, DateTimeKind.Utc),
                            QueueId = 1,
                            Status = 2
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2026, 2, 16, 8, 40, 0, 0, DateTimeKind.Utc),
                            QueueId = 3,
                            Status = 2
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2026, 2, 16, 8, 50, 0, 0, DateTimeKind.Utc),
                            QueueId = 1,
                            Status = 0
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2026, 2, 16, 8, 55, 0, 0, DateTimeKind.Utc),
                            QueueId = 2,
                            Status = 0
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2026, 2, 16, 8, 58, 0, 0, DateTimeKind.Utc),
                            QueueId = 3,
                            Status = 0
                        });
                });

            modelBuilder.Entity("Dashboard.Domain.Entities.Queue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Queues");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Technical Support"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Sales"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Billing"
                        });
                });

            modelBuilder.Entity("Dashboard.Domain.Entities.Call", b =>
                {
                    b.HasOne("Dashboard.Domain.Entities.Agent", "Agent")
                        .WithMany("_agentCalls")
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Dashboard.Domain.Entities.Queue", "Queue")
                        .WithMany("_queueCalls")
                        .HasForeignKey("QueueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agent");

                    b.Navigation("Queue");
                });

            modelBuilder.Entity("Dashboard.Domain.Entities.Agent", b =>
                {
                    b.Navigation("_agentCalls");
                });

            modelBuilder.Entity("Dashboard.Domain.Entities.Queue", b =>
                {
                    b.Navigation("_queueCalls");
                });
#pragma warning restore 612, 618
        }
    }
}
